version: '3'
services:
  db:
    container_name: accounting-postgres
    restart: always
    image: postgres:12.11-alpine
    env_file:
      - db.env
    volumes:
      - postgres-data:/var/lib/postgresql/data/
      - ./scripts:/tmp/scripts
  backend:
    container_name: accounting-backend
    image: nikitadanilenko/accounting:latest
    ports:
      - "9001:9000"
    env_file:
      - deployment.env
    depends_on:
      - db
  frontend:
    container_name: accounting-frontend
    image: nikitadanilenko/accounting-frontend:latest
    ports:
      - "9002:80"
    restart: always
volumes:
  postgres-data:
  scripts:

